
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= Watson AlchemyLanguage Service Connector API Reference

+++
The IBM Watson™ AlchemyLanguage service is a collection of text analysis functions that derive semantic information
from your content. You can input text, HTML, or a public URL and leverage sophisticated natural language processing
techniques to get a quick high-level understanding of your content and obtain detailed insights such as sentiment for
detected entities and keywords.
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.6.0 or higher
|======================


== Configs
---
=== Configuration
`<watson-alchemy-language:config>`


`Connection Management` 



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| apiKey | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The API Key retrieved from IBM Bluemix that will be used in all the request.+++ |   | *x*{nbsp}
|======================



== Processors

---

=== Authors
`<watson-alchemy-language:authors>`




+++
Get author names from a web page or HTML content.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#authors">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentAuthors+++ | +++A list of detected authors in a web page or HTML content.+++
|======================




---

=== Entities
`<watson-alchemy-language:entities>`




+++
Extract entities from a text, web page or HTML content.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#entities">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/EntitiesRequest.html">EntitiesRequest</a>+++ | +++Request with all the options for entities operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Entities+++ | +++A list of detected entities in a text, web page or HTML content.+++
|======================




---

=== Date extraction
`<watson-alchemy-language:date-extraction>`




+++
Extract Dates from a text, web page or content in an URL.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#date-extraction">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
dateExtractionRequest icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/DateExtractionRequest.html">DateExtractionRequest</a>+++ | +++Request with all the options for a date extraction operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Dates+++ | +++A list of detected dates in the text, web page or HTML content.+++
|======================




---

=== Feed detection
`<watson-alchemy-language:feed-detection>`




+++
Get feeds from a url.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#feed-detection">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
url icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The <code>URL</code> to process.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Feeds+++ | +++A list of detected RSS/ATOM links in web page.+++
|======================




---

=== Concepts
`<watson-alchemy-language:concepts>`




+++
Extract concepts from a web page or plain text.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#concepts">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/ConceptsRequest.html">ConceptsRequest</a>+++ | +++Request with all the options for a concept operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Concepts+++ | +++A list of detected high level concepts used in the text, web page or HTML content.+++
|======================




---

=== Targeted sentiment
`<watson-alchemy-language:targeted-sentiment>`




+++
Analyze sentiment for targeted phrases in a web page, HTML, or plain text. Supported languages: Arabic, English,
French, German, Italian, Portuguese, Russian, Spanish.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#targeted-sentiment">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/TargetedSentimentRequest.html">TargetedSentimentRequest</a>+++ | +++Request with all the options for the targeted sentiment operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentSentiment+++ | +++The sentiment expressed in the targeted phrase in the text, web page or HTML content.+++
|======================




---

=== Keywords
`<watson-alchemy-language:keywords>`




+++
Extract keywords from a web pages, HTML or plain text.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#keywords">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/KeywordsRequest.html">KeywordsRequest</a>+++ | +++Request with all the options for the keywords operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Keywords+++ | +++A list of detected keywords in a text, web page or HTML content.+++
|======================




---

=== Microformats
`<watson-alchemy-language:microformats>`




+++
Get Microformats from a text, web page or content in an URL.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#microformats">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/MicroformatsRequest.html">MicroformatsRequest</a>+++ | +++Request with all the options for the microformats operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Microformats+++ | +++A list of detected microformats in a text, web page or HTML content.+++
|======================




---

=== Relations
`<watson-alchemy-language:relations>`




+++
Extract Subject-Action-Object relations from a web page, HTML, or plain text. Supported languages: English,
Spanish
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#microformats">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/SAORelationsRequest.html">SAORelationsRequest</a>+++ | +++Request with all the options for the Subject-Action-Object relations operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++SAORelations+++ | +++A list of detected Subject-Action-Object relations in the text, web page or HTML content.+++
|======================




---

=== Publication date
`<watson-alchemy-language:publication-date>`




+++
Get the publication date of a web page or HTML document.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#publication_date">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentPublicationDate+++ | +++The publication date of the web page or HTML content.+++
|======================




---

=== Sentiment analysis
`<watson-alchemy-language:sentiment-analysis>`




+++
Analyze the overall sentiment of a web page, HTML, or plain text.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#sentiment">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/SentimentAnalysisRequest.html">SentimentAnalysisRequest</a>+++ | +++Request with all the options for the sentiment analysis operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentSentiment+++ | +++The general sentiment expressed in the text, web page or HTML content.+++
|======================




---

=== Typed relations
`<watson-alchemy-language:typed-relations>`




+++
Use custom models to identify typed relations between detected entities from a web page, HTML, or plain text.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#typed_relations">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/TypedRelationsRequest.html">TypedRelationsRequest</a>+++ | +++Request with all the options for the typed relations operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++TypedRelations+++ | +++A list of detected Subject-Action-Object relations in the text, web page or HTML content.+++
|======================




---

=== Language detection
`<watson-alchemy-language:language-detection>`




+++
Detect the language of a web page, HTML, or plain text.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#language">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/LanguageDetectionRequest.html">LanguageDetectionRequest</a>+++ | +++Request with all the options for the language detection operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Language+++ | +++The detected languages in a text, web page or HTML content.+++
|======================




---

=== Title extraction
`<watson-alchemy-language:title-extraction>`




+++
Extract the page title from a web page or HTML.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#title_extraction">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/TitleExtractionRequest.html">TitleExtractionRequest</a>+++ | +++Request with all the options for the title extraction operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentTitle+++ | +++The title of the web page or HTML content.+++
|======================




---

=== Text extraction
`<watson-alchemy-language:text-extraction>`




+++
Extract the main body text from a web page or HTML.
<a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#text_cleaned">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/TextExtractionRequest.html">TextExtractionRequest</a>+++ | +++Request with all the options for the text extraction operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentText+++ | +++The extracted text.+++
|======================




---

=== Raw text extraction
`<watson-alchemy-language:raw-text-extraction>`




+++
Extract the main body raw text from a web page or HTML.
<a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#text_raw">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process.+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentText+++ | +++The extracted text.+++
|======================




---

=== Taxonomies
`<watson-alchemy-language:taxonomies>`




+++
Categorize a web page into a 5-level taxonomy
<a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#taxonomy">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/TaxonomiesRequest.html">TaxonomiesRequest</a>+++ | +++Request with all the options for the taxonomies operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Taxonomies+++ | +++A list of detected taxonomies in the text, web page or HTML content.+++
|======================




---

=== Emotion analysis
`<watson-alchemy-language:emotion-analysis>`




+++
Detect emotions implied in the text of a web page
<a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#emotion_analysis">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/EmotionAnalysisRequest.html">EmotionAnalysisRequest</a>+++ | +++Request with all the options for the emotion analysis operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentEmotion+++ | +++A list of all the detected emotions in the text, web page or HTML content.+++
|======================




---

=== Combined call
`<watson-alchemy-language:combined-call>`




+++
Analyze text, HTML, or web page content with multiple text analysis operations. Any parameters for the extract
methods can also be passed.
<a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#combined-call">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonalchemylanguage/model/CombinedCallRequest.html">CombinedCallRequest</a>+++ | +++Request with all the options for a combine call operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++CombinedResults+++ | +++The combined results for all the operations specified in the extract parameter.+++
|======================














