
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= Watson AlchemyLanguage Service Connector API Reference

+++
The IBM Watson™ AlchemyLanguage service is a collection of text analysis functions that derive semantic information
from your content. You can input text, HTML, or a public URL and leverage sophisticated natural language processing
techniques to get a quick high-level understanding of your content and obtain detailed insights such as sentiment for
detected entities and keywords.
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.6.0 or higher
|======================


== Configs
---
=== Configuration
`<watson-alchemy-language:config>`


`Connection Management` 



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| apiKey | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | ++++++ |   | *x*{nbsp}
|======================



== Processors

---

=== Authors
`<watson-alchemy-language:authors>`




+++
Get author names from a webpage or HTML content.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#authors"> #authors </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:authors
+++

==== XML Sample
[source,xml]
----
<watson-alchemy-language:authors config-ref="ref"  source="www.url.com" doc:name="Watson AlchemyLanguage Service" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or url to process+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentAuthors+++ | +++return A list of extracted DocumentAuthors+++
|======================




---

=== Entities
`<watson-alchemy-language:entities>`




+++
Extract entities from a text or a webpage.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#entities"> #entities </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:entities
+++

==== XML Sample
[source,xml]
----
<watson-alchemy-language:entities config-ref="ref"
	source="IBM Watson won the Jeopardy television show hosted by Alex Trebek"
	maxRetrieve="5" doc:name="Watson AlchemyLanguage Service"/>
----

    
                                                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text or url to process+++ | #[payload] | {nbsp}




| 
maxRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Maximum number of entities to return (default = 50)+++ |  | {nbsp}




| 
coreference  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to treat coreferences as separate entities (coreferences are resolved into detected entities by default)+++ |  | {nbsp}




| 
disambiguate  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to hide entity disambiguation information in the response+++ |  | {nbsp}




| 
knowledgeGraph  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to include knowledge graph information in the results. This incurs an additional transaction charge+++ |  | {nbsp}




| 
linkedData  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to hide Linked Data content links in the response+++ |  | {nbsp}




| 
quotations  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to include quotations that are linked to detected entities+++ |  | {nbsp}




| 
sentiment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to analyze the sentiment towards each detected entity. This incurs an additional transaction charge+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response+++ |  | {nbsp}




| 
structuredEntities  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to ignore structured entities, such as Quantity, EmailAddress, TwitterHandle, Hashtag, and IPAddress+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Entities+++ | +++return Entities+++
|======================




---

=== Date extraction
`<watson-alchemy-language:date-extraction>`




+++
Extract Dates from a text, webpage or content in an url.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#date-extraction"> #date-extraction </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:dateExtraction
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, html or url to process.+++ | #[payload] | {nbsp}




| 
anchorDate  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The date to use as "today" when interpreting phrases in the text like "next tuesday." Format: <code>yyyy-mm-dd hh:mm:ss</code>+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Dates+++ | +++return Dates+++
|======================




---

=== Feed detection
`<watson-alchemy-language:feed-detection>`




+++
Get feeds from a url.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#feed-detection"> #feed-detection </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:feedDetection
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
url icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The <code>URL</code> to process.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Feeds+++ | +++return Feeds+++
|======================




---

=== Concepts
`<watson-alchemy-language:concepts>`




+++
Extract concepts from a webpage or plain text.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#concepts"> #concepts </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:concepts
+++

==== XML Sample
[source,xml]
----
<watson-alchemy-language:concepts config-ref="ref"
	source="IBM Watson won the Jeopardy television show hosted by Alex Trebek"
	maxRetrieve="5" doc:name="Watson AlchemyLanguage Service"/>
----

    
                                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text or url to process+++ | #[payload] | {nbsp}




| 
maxRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Maximum number of entities to return (default = 50) detected entities by default)+++ |  | {nbsp}




| 
knowledgeGraph  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to include knowledge graph information in the results. This incurs an additional transaction charge+++ |  | {nbsp}




| 
linkedData  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to hide Linked Data content links in the response+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response TwitterHandle, Hashtag, and IPAddress+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Concepts+++ | +++return Concepts+++
|======================




---

=== Targeted sentiment
`<watson-alchemy-language:targeted-sentiment>`




+++
Analyze sentiment for targeted phrases in a webpage, HTML, or plain text. Supported languages: Arabic, English,
French, German, Italian, Portuguese, Russian, Spanish.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#targeted-sentiment"> #targeted-sentiment </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:targetedSentiment
+++


    
                        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, HTML or URL to process.+++ | #[payload] | {nbsp}




| 
target  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Target phrase. The service will return sentiment information for the phrase that is found in the source text. @param target Target phrase. The service will return sentiment information for the phrase that is found in the source text.+++ |  | *x*{nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when <code>sourceText</code> is set to cquery.+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when <code>sourceText</code> is set to one of the XPath values.+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentSentiment+++ | +++return DocumentSentiment+++
|======================




---

=== Keywords
`<watson-alchemy-language:keywords>`




+++
Extract keywords from a webpages, HTML or plain text.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#keywords"> #keywords </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:keywords
+++

==== XML Sample
[source,xml]
----
<watson-alchemy-language:keywords config-ref="ref"
	source="The polymer is made by a company called Papa from Australia"
	maxRetrieve="10" knowledgeGraph="1" doc:name="Watson AlchemyLanguage Service"/>
----

    
                                
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, HTML or URL to process.+++ | #[payload] | {nbsp}




| 
maxRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Maximum number of entities to return (default = 50) detected entities by default).+++ |  | {nbsp}




| 
knowledgeGraph  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to include knowledge graph information in the results.+++ |  | {nbsp}




| 
sentiment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to analyze the sentiment towards each detected entity.+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when <code>sourceText</code> is set to cquery.+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when <code>sourceText</code> is set to one of the XPath values.+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Keywords+++ | +++return Keywords+++
|======================




---

=== Microformats
`<watson-alchemy-language:microformats>`




+++
Get Microformats from a text, webpage or content in an url.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#microformats"> #microformats </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:microformats
+++

==== XML Sample
[source,xml]
----
<watson-alchemy-language:microformats config-ref="ref"
	source="http://microformats.org/wiki/hcard"
	doc:name="Watson AlchemyLanguage Service"/>
----

    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, html or url to process.+++ | #[payload] | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Microformats+++ | +++return Microformats+++
|======================




---

=== Relations
`<watson-alchemy-language:relations>`




+++
Extract Subject-Action-Object relations from a webpage, HTML, or plain text. Supported languages: English,
Spanish
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#microformats"> #microformats </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:relations
+++

==== XML Sample
[source,xml]
----
<watson-alchemy-language:relations config-ref="ref"
	source="http://www.admios.com/admios-blog/"
	maxRetrieve="10" knowledgeGraph="true" doc:name="Watson AlchemyLanguage Service"/>
----

    
                                                            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++One of these is required. Pass HTML content in html, a public facing URL in url, or plain text in text.+++ | #[payload] | {nbsp}




| 
maxRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Maximum number of relations to return (default = 50, maximum = 100)+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}




| 
keywords  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to identify keywords in detected relations. <b>This incurs an additional transaction charge</b>+++ |  | {nbsp}




| 
entities  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to identify named entities in detected relations. <b>This incurs an additional transaction charge.</b>+++ |  | {nbsp}




| 
requireEntities  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to restrict results to relations that contain at least one named entity.+++ |  | {nbsp}




| 
coreference  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this treat coreferences as separate entities (coreferences are resolved into detected entities by default).+++ |  | {nbsp}




| 
disambiguate  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to hide entity disambiguation information in the response.+++ |  | {nbsp}




| 
knowledgeGraph  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include knowledge graph information in the results. <b>This incurs an additional transaction charge.</b>+++ |  | {nbsp}




| 
hideLinkedData  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to hide Linked Data contents links in the response.+++ |  | {nbsp}




| 
analyzeSentiment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to analyze the sentiment towards each result.+++ |  | {nbsp}




| 
excludeEntityFromSentimentAnalysis  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to exclude named entity text from sentiment analysis. For exapmle, do not analyze "New" in "New York".+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when sourceText is set to cquery.+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values.+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the web page.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++SAORelations+++ | +++return an array of detected relations.+++
|======================




---

=== Publication date
`<watson-alchemy-language:publication-date>`




+++
Get the publication date of a webpage or HTML document.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#publication_date"> #publication_date </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:publicationDate
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or url to process+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentPublicationDate+++ | +++return DocumentPublicationDate+++
|======================




---

=== Sentiment analysis
`<watson-alchemy-language:sentiment-analysis>`




+++
Analyze the overall sentiment of a webpage, HTML, or plain text.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#sentiment"> #sentiment </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:sentimentAnalysis
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, HTML document or url to process+++ | #[payload] | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentSentiment+++ | +++return DocumentSentiment+++
|======================




---

=== Typed relations
`<watson-alchemy-language:typed-relations>`




+++
Use custom models to identify typed relations between detected entities from a webpage, HTML, or plain text.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#typed_relations"> #typed_relations </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:typedRelations
+++


    
            
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, HTML document or url to process+++ | #[payload] | {nbsp}




| 
model  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The unique alphanumeric identifier for your custom model+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++TypedRelations+++ | +++return TypedRelations+++
|======================




---

=== Language detection
`<watson-alchemy-language:language-detection>`




+++
Detect the language of a webpage, HTML, or plain text.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#language"> #language </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:languageDetection
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text, HTML or URL to process.+++ | #[payload] | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when <code>sourceText</code> is set to cquery.+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when <code>sourceText</code> is set to one of the XPath values.+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Language+++ | +++return Language+++
|======================




---

=== Title extraction
`<watson-alchemy-language:title-extraction>`




+++
Extract the page title from a webpage or HTML.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#title_extraction"> #title_extraction </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:titleExtraction
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process.+++ | #[payload] | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to include the source text in the response.+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentTitle+++ | +++return DocumentTitle+++
|======================




---

=== Text extraction
`<watson-alchemy-language:text-extraction>`




+++
Extract the main body text from a webpage or HTML.
API Doc: <a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#text_cleaned"> #text_cleaned </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:textExtraction
+++


    
                        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process.+++ |  | *x*{nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraint query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Determines how to obtain the source text from the webpage+++ |  | {nbsp}




| 
extractLinks  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Set this to 1 to include hyperlinks in the extracted text+++ |  | {nbsp}




| 
useMetaData  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Comment for useMetaData+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentText+++ | +++return DocumentText+++
|======================




---

=== Raw text extraction
`<watson-alchemy-language:raw-text-extraction>`




+++
Extract the main body raw text from a webpage or HTML.
API Doc: <a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#text_raw"> #text_raw </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:rawTextExtraction
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process.+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentText+++ | +++return DocumentText+++
|======================




---

=== Taxonomies
`<watson-alchemy-language:taxonomies>`




+++
Categorize a webpage into a 5-level taxonomy
API Doc: <a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#taxonomy"> #taxonomy </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:taxonomy
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process.+++ |  | *x*{nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Set this to 1 to include the source text in the response+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraint query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Determines how to obtain the source text from the webpage+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++Taxonomies+++ | +++return Taxonomies+++
|======================




---

=== Emotion analysis
`<watson-alchemy-language:emotion-analysis>`




+++
Detect emotions implied in the text of a webpage
API Doc: <a href="https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#emotion_analysis"> #emotion_analysis </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:emotionalAnalysis
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The HTML or URL to process.+++ |  | *x*{nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Set this to 1 to include the source text in the response+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraint query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Determines how to obtain the source text from the webpage+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DocumentEmotion+++ | +++return DocumentEmotion+++
|======================




---

=== Combined call
`<watson-alchemy-language:combined-call>`




+++
Analyze text, HTML, or webpage content with multiple text analysis operations. Any parameters for the extract
methods can also be passed.
API Doc: <a href="http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/#combined-call"> #combined-call </a>
../../../doc/watson-alchemy-language-connector.xml.sample watson-alchemy-language:combinedCall
+++


    
                                                                        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
source icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The text or url to process+++ | #[payload] | {nbsp}




| 
extract  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Comma separated list of any of the following methods: authors, concepts (default), dates, doc-emotion, entities (default), feeds, keywords (default), pub-date, relations, typed-rels, doc-sentiment, taxonomy (default), title+++ |  | {nbsp}




| 
maxRetrieve  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Maximum number of entities to return (default = 50)+++ |  | {nbsp}




| 
keywords  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to identify keywords in detected relations. <b>This incurs an additional transaction charge</b>+++ |  | {nbsp}




| 
entities  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to identify named entities in detected relations. <b>This incurs an additional transaction charge.</b>+++ |  | {nbsp}




| 
requireEntities  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Check this to restrict results to relations that contain at least one named entity.+++ |  | {nbsp}




| 
coreference  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to treat coreferences as separate entities (coreferences are resolved into detected entities by default)+++ |  | {nbsp}




| 
disambiguate  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to hide entity disambiguation information in the response+++ |  | {nbsp}




| 
knowledgeGraph  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to include knowledge graph information in the results. This incurs an additional transaction charge+++ |  | {nbsp}




| 
linkedData  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to hide Linked Data content links in the response+++ |  | {nbsp}




| 
quotations  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to include quotations that are linked to detected entities+++ |  | {nbsp}




| 
sentiment  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 1 to analyze the sentiment towards each detected entity. This incurs an additional transaction charge+++ |  | {nbsp}




| 
showSourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Set this to 1 to include the source text in the response+++ |  | {nbsp}




| 
structuredEntities  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Set this to 0 to ignore structured entities, such as Quantity, EmailAddress, TwitterHandle, Hashtag, and IPAddress+++ |  | {nbsp}




| 
anchorDate  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The date to use as "today" when interpreting phrases in the text like "next tuesday.". Format: yyyy-mm-dd hh:mm:ss+++ |  | {nbsp}




| 
cquery  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A visual constraints query to apply to the web page. Required when sourceText is set to cquery+++ |  | {nbsp}




| 
xpath  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An XPath query to apply to the web page. Required when sourceText is set to one of the XPath values+++ |  | {nbsp}




| 
sourceText  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++How to obtain the source text from the webpage+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++CombinedResults+++ | +++return CombinedResults+++
|======================














