////
Watson - Alchemy language Connector User Guide.
////

= IBM Watson - Alchemy language Connector

:keywords: add_keywords_separated_by_commas
:imagesdir: ./_images
:toc: macro
:toclevels: 3

////
Image names follow "image:". Identify images using the connector name, preferably without the word "connector"
URLs should always follow "link:"
////

// Dropdown for Connector Version
//  Children: Technical Reference / Demos

toc::[]

//Global rule: the word "connector" should be lower case except when appearing in titles, important URL anchors, and after a MuleSoft tradename such as "Anypoint".
== Introduction
AlchemyLanguage is a collection of text analysis functions that derive semantic information from your content.
You can input text, HTML, or a public URL and leverage sophisticated natural language processing techniques to
get a quick high-level understanding of your content and obtain detailed insights such as directional sentiment from entity to object.
With this connector you have full access to AlchemyLanguage methods.


Read through this user guide to understand how to set up and configure a basic flow using the connector.
Check features, compatibility and versions of the connector using the https://github.com/Admios/watson-alchemy-language-connector/blob/master/CHANGELOG.md[Release Notes].
Connector API link:/doc/API_Reference/[Technical Reference] or check our link:/demo_app[demo applications].

== Prerequisites
* Anypoint Studio 6.0.x
* Oracle Java JDK 7.0

=== Extensions for Anypoint Studio
* Anypoint DevKit 1.1.4+
* Mule Server Runtime 3.8.0 EE

* Already have an account in IMB Bluemix, you may create it https://www.ibm.com/account/us-en/[here].
* Have an Watson API Key for Alchemy Language https://new-console.ng.bluemix.net/dashboard/watson[Watson page].


== Install the Connector

=== Inside Anypoint Studio
You can install the connector in Anypoint Studio using the menu option inside Anypoint Studio,
Just click on Help -> Install New Software

. In field *works with* select: _Anypoint Connectors Update Site_
. In the dropdown *Select* look for _Watson IBM Alchemy Language Connector_
. Check the box.
. Click next to review the software to install
. Click next to accept the license
. Choose _I accept the terms of the license agreement_.
. Click Finish

Is prefer to restart Anypoint Studio after the install.


=== Using the Connector in a Mavenized Mule App

If you are coding a Mavenized Mule application, this XML snippet must be included in your `pom.xml` file.

[source,xml,linenums]
----
<dependency>
	<groupId>com.admios.connector</groupId>
	<artifactId>watson-alchemy-language-connector</artifactId>
	<version>1.0.0-SNAPSHOT</version>
</dependency>
----
